package requete;

public enum RequeteSocket {

    COMPTE_CREE("COMPTE_CREE"),
    DEMANDER_CREER_COMPTE("DEMANDER_CREER_COMPTE"),
    ACCEPTER_CREER_COMPTE("ACCEPTER_CREER_COMPTE"),
    SAUVEGARDER_PROFIL("SAUVEGARDER_PROFIL"),
    MISE_A_JOUR_PROFIL("MISE_A_JOUR_PROFIL"),
    RECHERCHER_COMPTES("RECHERCHER_COMPTES"),
    DEMANDER_PROFIL("DEMANDER_PROFIL"),
    DEMANDER_SUIVRE("DEMANDER_SUIVRE"),
    DEMANDER_PLUS_SUIVRE("DEMANDER_PLUS_SUIVRE"),
    METTRE_A_JOUR_SUIVI("METTRE_A_JOUR_SUIVI"),
    LIKER_PUBLICATION("LIKER_PUBLICATION"),
    DISLIKER_PUBLICATION("DISLIKER_PUBLICATION"),
    SUPPRIMER_PUBLICATION("SUPPRIMER_PUBLICATION"),
    PUBLIER_PUBLICATION("PUBLIER_PUBLICATION"),
    AVOIR_DERNIER_MESSAGE("AVOIR_DERNIER_MESSAGE"),
    DEMANDE_MESSAGE("DEMANDE_MESSAGE"),
    ENVOYER_MESSAGE("ENVOYER_MESSAGE"),
    ENVOYER_VOCAL("ENVOYER_VOCAL"),
    DECONNEXION("DECONNEXION"),
    SUPPRIMER_MESSAGE("SUPPRIMER_MESSAGE"),;

    private final String requete;

    RequeteSocket(String requete) {
        this.requete = requete;
    }

    public String getRequete() {
        return this.requete;
    }

}
