-- Insert into UTILISATEUR table
INSERT INTO UTILISATEUR (NOM_USER, FOLLEWER, FOLLOWING) VALUES ('Alice', 10, 5);
INSERT INTO UTILISATEUR (NOM_USER, FOLLEWER, FOLLOWING) VALUES ('Bob', 20, 15);
INSERT INTO UTILISATEUR (NOM_USER, FOLLEWER, FOLLOWING) VALUES ('Charlie', 5, 8);
INSERT INTO UTILISATEUR (NOM_USER, FOLLEWER, FOLLOWING) VALUES ('David', 15, 10);
INSERT INTO UTILISATEUR (NOM_USER, FOLLEWER, FOLLOWING) VALUES ('Eva', 8, 12);

-- Insert into MESSAGE table
INSERT INTO MESSAGE (NOM_USER, CONTENUE, DATE_MESSAGE, LIKES) VALUES ('Alice', 'Hello followers!', '2023-01-01 12:00:00', 5);
INSERT INTO MESSAGE (NOM_USER, CONTENUE, DATE_MESSAGE, LIKES) VALUES ('Alice', 'SQL is fun!', '2023-02-15 14:30:00', 8);
INSERT INTO MESSAGE (NOM_USER, CONTENUE, DATE_MESSAGE, LIKES) VALUES ('Charlie', 'Enjoying the day!', '2023-03-10 09:45:00', 3);
INSERT INTO MESSAGE (NOM_USER, CONTENUE, DATE_MESSAGE, LIKES) VALUES ('David', 'Coding all night!', '2023-04-05 03:20:00', 12);
INSERT INTO MESSAGE (NOM_USER, CONTENUE, DATE_MESSAGE, LIKES) VALUES ('Eva', 'Traveling the world!', '2023-05-20 18:00:00', 7);