CREATE TABLE UTILISATEUR (
    NOM_USER VARCHAR(25) UNIQUE NOT NULL,
    FOLLEWER INT,
    FOLLOWING INT,
    PRIMARY KEY (NOM_USER)

);

CREATE TABLE MESSAGE (
    ID_MESSAGE INT AUTO_INCREMENT,
    NOM_USER VARCHAR(25) NOT NULL,
    CONTENUE VARCHAR(140) NOT NULL,
    DATE_MESSAGE DATETIME NOT NULL,
    LIKES INT,
    PRIMARY KEY (ID_MESSAGE),
    FOREIGN KEY (NOM_USER) REFERENCES UTILISATEUR(NOM_USER)
);

