CREATE TABLE UTILISATEUR  (
    NOM_USER VARCHAR(25) UNIQUE NOT NULL,
    PRIMARY KEY (NOM_USER)
);

CREATE TABLE FOLLOW  (
    ID_FOLLOW INT AUTO_INCREMENT,
    NOM_USER VARCHAR(25) NOT NULL,
    NOM_FOLLOW VARCHAR(25) NOT NULL,
    PRIMARY KEY (ID_FOLLOW),
    FOREIGN KEY (NOM_USER) REFERENCES UTILISATEUR(NOM_USER),
    FOREIGN KEY (NOM_FOLLOW) REFERENCES UTILISATEUR(NOM_USER)
);

CREATE TABLE MESSAGE (
    ID_MESSAGE INT AUTO_INCREMENT,
    NOM_USER VARCHAR(25) NOT NULL,
    CONTENUE VARCHAR(140) NOT NULL,
    DATE_MESSAGE DATETIME NOT NULL,
    LIKES INT,
    PRIMARY KEY (ID_MESSAGE),
    FOREIGN KEY (NOM_USER) REFERENCES UTILISATEUR(NOM_USER)
);

