DROP TABLE IF EXISTS `likes`;
DROP TABLE IF EXISTS `commentaires`;
DROP TABLE IF EXISTS `follows`;
DROP TABLE IF EXISTS `messages`;
DROP TABLE IF EXISTS `publications`;
DROP TABLE IF EXISTS `comptes`;
