-- Insert into UTILISATEUR table
INSERT INTO UTILISATEUR (NOM_USER) VALUES ('Alice');
INSERT INTO UTILISATEUR (NOM_USER) VALUES ('Bob');
INSERT INTO UTILISATEUR (NOM_USER) VALUES ('Charlie');
INSERT INTO UTILISATEUR (NOM_USER) VALUES ('David');
INSERT INTO UTILISATEUR (NOM_USER) VALUES ('Eva');

-- Insert into MESSAGE table
INSERT INTO MESSAGE (NOM_USER, CONTENUE, DATE_MESSAGE, LIKES) VALUES ('Alice', 'Hello followers!', '2023-01-01 12:00:00', 5);
INSERT INTO MESSAGE (NOM_USER, CONTENUE, DATE_MESSAGE, LIKES) VALUES ('Alice', 'SQL is fun!', '2023-02-15 14:30:00', 8);
INSERT INTO MESSAGE (NOM_USER, CONTENUE, DATE_MESSAGE, LIKES) VALUES ('Charlie', 'Enjoying the day!', '2023-03-10 09:45:00', 3);
INSERT INTO MESSAGE (NOM_USER, CONTENUE, DATE_MESSAGE, LIKES) VALUES ('David', 'Coding all night!', '2023-04-05 03:20:00', 12);
INSERT INTO MESSAGE (NOM_USER, CONTENUE, DATE_MESSAGE, LIKES) VALUES ('Eva', 'Traveling the world!', '2023-05-20 18:00:00', 7);